#!/bin/bash

usage() {
  echo "Usage: $0 -r rate -w window_size -s shift_size -n num_banks -c num_coef -o outdir files" >&2
  exit 1
}

cmd="$0 $@"

while getopts "r:w:s:n:c:o:" opt; do
  case $opt in
    r)
      rate=$OPTARG
      ;;
    w)
      wsize=$OPTARG
      ;;
    s)
      ssize=$OPTARG
      ;;
    n)
      nbanks=$OPTARG
      ;;
    c)
      csize=$OPTARG
      ;;
    o)
      outdir=$OPTARG
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

files=$@

nure='^[0-9]+$'
[[ $rate =~ $nure ]] && [[ $wsize =~ $nure ]] \
  && [[ $ssize =~ $nure ]] && [[ $nbanks =~ $nure ]] \
  && [[ $csize =~ $nure ]] \
  && [[ -n $files ]] && [[ -n $outdir ]] || usage

if [[ -d $outdir ]]; then
  echo "Error: directory $outdir exists" >&2
  exit 1
elif [[ -e $outdir ]]; then
  echo "Error: file $outdir exists" >&2
  exit 1
else
  mkdir "$outdir"
fi

echo "# this file and the data in this folder is generated by the following command" > "${outdir}/README"
echo "# $cmd" >> "${outdir}/README"
echo "Feature: MFCC" >> "${outdir}/README"
echo -n "Date: " >> "${outdir}/README"
date >> "${outdir}/README"
echo "Dimension: $csize" >> "${outdir}/README"
echo "Format: double" >> "${outdir}/README"
echo "Sample Rate: $rate" >> "${outdir}/README"
echo "Window Size: $wsize" >> "${outdir}/README"
echo "Shift Size: $ssize" >> "${outdir}/README"
echo "Number of Filter Banks: $nbanks" >> "${outdir}/README"
echo "Begin Index of Coefficients: 1" >> "${outdir}/README"
echo "Number of Coefficients: $csize" >> "${outdir}/README"

echo "# this file records the raw media file of the feature data" > "${outdir}/SOURCES"

id=0
for file in $files; do
  echo "Processing $file" >&2
  fname=${file##*/}
  fname=${fname%.*}
  class=${fname%_*}
  dest="${class}_${id}.fvec"
  echo "$dest < $file" >> "${outdir}/SOURCES"
  gst-launch-1.0 -q filesrc location="$file" ! avidemux name=demux \
    demux.audio_0 ! decodebin ! audioresample ! audio/x-raw,rate=$rate ! audioconvert \
    ! mfcc wsize=$wsize ssize=$ssize banks=$nbanks cbegin=1 csize=$csize location="$outdir/$dest" ! fakesink \
    || exit 1
  id=$((id + 1))
done

