#!/bin/bash

usage() {
  echo "Usage: $0 -w window_size -s shift_size -n num_banks -c num_coef [-p pattern] filelist outdir" >&2
  exit 1
}

cmd="$0 $@"

while getopts "w:s:n:c:p:" opt; do
  case $opt in
    w)
      wsize=$OPTARG
      ;;
    s)
      ssize=$OPTARG
      ;;
    n)
      nbanks=$OPTARG
      ;;
    c)
      csize=$OPTARG
      ;;
    p)
      pattern=$OPTARG
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

filelist=$1
outdir=$2

nure='^[0-9]+$'
[[ $wsize =~ $nure ]] && [[ $ssize =~ $nure ]] && [[ $nbanks =~ $nure ]] && [[ $csize =~ $nure ]] || usage

[[ -n $outdir ]] || usage

if ! [[ -f $filelist ]]; then
  echo "Error: file $filelist does not exist" >&2
  exit 1
fi

if [[ -d $outdir ]]; then
  echo "Warning: directory $outdir exists and will be overwritted." >&2
elif [[ -e $outdir ]]; then
  echo "Error: file $outdir exists" >&2
  exit 1
else
  mkdir "$outdir"
fi

echo "# this file and the data in this folder is generated by the following command" > "${outdir}/README"
echo "# $cmd" >> "${outdir}/README"
echo "Feature: MFCC" >> "${outdir}/README"
echo "Dimension: $csize" >> "${outdir}/README"
echo "Format: double" >> "${outdir}/README"
echo "Window Size: $wsize" >> "${outdir}/README"
echo "Shift Size: $ssize" >> "${outdir}/README"
echo "Number of Filter Banks: $nbanks" >> "${outdir}/README"
echo "Begin Index of Coefficients: 1" >> "${outdir}/README"
echo "Number of Coefficients: $csize" >> "${outdir}/README"

echo "# this file records the raw audio file of the feature data" > "${outdir}/SOURCES"

id=0
for file in `grep "$pattern" "$filelist"`; do
  class=`echo $file | awk -F'/' '{print $7}'`
  dest="${class}_${id}.fvec"
  echo "$dest < $file" >> "${outdir}/SOURCES"
  gst-launch-1.0 -q filesrc location="$file" ! audio/x-raw,rate=8000,channels=1,format=S16LE ! audioconvert ! mfcc wsize=$wsize ssize=$ssize banks=$nbanks cbegin=1 csize=$csize location="$outdir/$dest" ! fakesink
  id=$((id + 1))
done

